# Generated by Django 4.2.7 on 2025-11-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(
                        db_index=True, help_text="Reference to order in Order Service"
                    ),
                ),
                (
                    "tracking_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("DHL", "DHL"),
                            ("Bluedart", "Bluedart"),
                            ("FedEx", "FedEx"),
                            ("DTDC", "DTDC"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shipping_address", models.TextField(blank=True, null=True)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="shipment.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "shipment_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["order_id", "status"], name="shipments_order_i_1ac412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["tracking_no"], name="shipments_trackin_0edf92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["created_at"], name="shipments_created_b63910_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipmenthistory",
            index=models.Index(
                fields=["shipment", "timestamp"], name="shipment_hi_shipmen_d70400_idx"
            ),
        ),
    ]
